CREATE TABLE IF NOT EXISTS items (
  id SERIAL PRIMARY KEY,
  text VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO items (text) VALUES 
  ('Tâche 1'), ('Tâche 2'), ('Tâche 3')
ON CONFLICT DO NOTHING;
